# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeof', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edit_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=60, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('level', models.IntegerField(default=0, verbose_name='Nível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='members',
            field=models.ManyToManyField(to='agromap_api.User'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='supervisor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='agromap_api.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agromap_api.Inspection'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='agromap_api.User'),
        ),
    ]
