# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=60, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('level', models.IntegerField(default=0, verbose_name='Nível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
