# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromap_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
