# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromap_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(default='Checked', max_length=40),
        ),
    ]
